<html>
<head>
<title>What Exceptions Cannot Be Caught by try-catch?</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">try-catch不能捕获哪些异常？</h1>
<blockquote>原文：<a href="https://javascript.plainenglish.io/what-exceptions-cannot-be-caught-by-try-catch-b33ecd9b5d74?source=collection_archive---------8-----------------------#2020-05-01">https://javascript.plainenglish.io/what-exceptions-cannot-be-caught-by-try-catch-b33ecd9b5d74?source=collection_archive---------8-----------------------#2020-05-01</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><div class=""><h2 id="9619" class="pw-subtitle-paragraph jn ip iq bd b jo jp jq jr js jt ju jv jw jx jy jz ka kb kc kd ke dk translated">掌握try-catch边界，使您的代码更加安全。</h2></div><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi kf"><img src="../Images/919182ec3805d86c7731ed7d83aafc28.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*kfsmBJIJqysKu4xy"/></div></div><figcaption class="kr ks gj gh gi kt ku bd b be z dk">Photo by <a class="ae kv" href="https://unsplash.com/@rojekilian?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Sarah Kilian</a> on <a class="ae kv" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></figcaption></figure><p id="6b3b" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">我们习惯于将代码包装在try-catch中，以防止程序由于各种可能的错误而中止。但是试捕不是万能的，我们要知道试捕不能做什么。</p><h1 id="f6db" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">1.无法捕捉语法错误</h1><p id="4a00" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">当代码报告错误时，如果线程尚未进入try-catch块，则无法捕获异常。</p><p id="29da" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">比如syntaxError，因为语法异常是在语法检查阶段报告的，线程执行没有进入try-catch代码块，自然无法捕捉到异常。</p><p id="fb61" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">示例:</p><pre class="kg kh ki kj gt mp mq mr ms aw mt bi"><span id="4079" class="mu lt iq mq b gy mv mw l mx my">try {<br/>    a.[]   <br/>} catch(e){<br/>    console.log("error",e);<br/>}</span></pre><p id="533f" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在上面的例子中，<code class="fe mz na nb mq b">a.[]</code>不是有效的语法，所以在语法的解析阶段会抛出一个异常。</p><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi nc"><img src="../Images/c852fc9ba991ed0d3ea5c8f56919cc62.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*NKXMWeBpRQo8NlyQhe5pVQ.png"/></div></div></figure><h1 id="be48" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">2.无法捕获异步代码中的异常</h1><p id="96ee" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">示例:</p><pre class="kg kh ki kj gt mp mq mr ms aw mt bi"><span id="8896" class="mu lt iq mq b gy mv mw l mx my">try {    <br/>  setTimeout(()=&gt;{<br/>    throw new Error('an asynchronous error');<br/>  }, 100)<br/>} catch(e) {<br/>    console.log('error: ',e);<br/>}</span></pre><p id="7e01" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">在此示例中，调用setTimeout回调函数时，try-catch语句结束，因此无法捕获异步回调函数中引发的异常。</p><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi nd"><img src="../Images/bce890bf58e5d40f95274ef96f2b3594.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*JXXnWL0nDVJ__68OuAucRQ.png"/></div></div></figure><h1 id="574f" class="ls lt iq bd lu lv lw lx ly lz ma mb mc jw md jx me jz mf ka mg kc mh kd mi mj bi translated">3.无法捕捉承诺的例外</h1><p id="fba6" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">示例1:</p><pre class="kg kh ki kj gt mp mq mr ms aw mt bi"><span id="d1ca" class="mu lt iq mq b gy mv mw l mx my">try {<br/>  new Promise((resolve, reject) =&gt; {<br/>    throw new Error('error from promise')<br/>  })</span><span id="591b" class="mu lt iq mq b gy ne mw l mx my">} catch (error) {<br/>  console.log('error:', error)<br/>}</span></pre><p id="3376" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">示例2:</p><pre class="kg kh ki kj gt mp mq mr ms aw mt bi"><span id="6409" class="mu lt iq mq b gy mv mw l mx my">try {<br/>  new Promise((resolve, reject) =&gt; {<br/>    setTimeout(() =&gt; {<br/>      throw new Error('error from promise')<br/>    }, 100)<br/>  })<br/>} catch (error) {<br/>  console.log('error:', error)<br/>}</span></pre><p id="3bfe" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">Promise对象中生成的所有异常(无论同步还是异步)都被Promise对象本身捕获，并交给<code class="fe mz na nb mq b">Promise.prototype.catch</code>处理。我们永远不能接受承诺之外的例外。</p><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi nf"><img src="../Images/13792b01db0edcb9006f2bb7a0332d72.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*zcnnsKx84Z1yJXHjix7swA.png"/></div></div></figure><figure class="kg kh ki kj gt kk gh gi paragraph-image"><div role="button" tabindex="0" class="kl km di kn bf ko"><div class="gh gi ng"><img src="../Images/81f54c664f3bf9a99af12895d5d6ebb4.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*Us1gscWvfcOMR-0UvvjNyg.png"/></div></div></figure><h2 id="c6cf" class="mu lt iq bd lu nh ni dn ly nj nk dp mc lf nl nm me lj nn no mg ln np nq mi nr bi translated"><strong class="ak">用简单英语写的JavaScript笔记</strong></h2><p id="c4c7" class="pw-post-body-paragraph kw kx iq ky b kz mk jr lb lc ml ju le lf mm lh li lj mn ll lm ln mo lp lq lr ij bi translated">我们已经推出了三种新的出版物！请关注我们的新出版物:<a class="ae kv" href="https://medium.com/ai-in-plain-english" rel="noopener"> <strong class="ky ir"> AI in Plain English </strong> </a>，<a class="ae kv" href="https://medium.com/ux-in-plain-english" rel="noopener"><strong class="ky ir">UX in Plain English</strong></a>，<a class="ae kv" href="https://medium.com/python-in-plain-english" rel="noopener"><strong class="ky ir">Python in Plain English</strong></a><strong class="ky ir"/>——谢谢，继续学习！</p><p id="a981" class="pw-post-body-paragraph kw kx iq ky b kz la jr lb lc ld ju le lf lg lh li lj lk ll lm ln lo lp lq lr ij bi translated">我们也一直有兴趣帮助推广高质量的内容。如果您有一篇文章想要提交给我们的任何出版物，请发送电子邮件至<a class="ae kv" href="mailto:submissions@plainenglish.io" rel="noopener ugc nofollow" target="_blank"><strong class="ky ir">submissions @ plain English . io</strong></a><strong class="ky ir"/>，使用您的Medium用户名，我们会将您添加为作者。另外，请让我们知道您想加入哪个/哪些出版物。</p></div></div>    
</body>
</html>